/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ijk-n4.3-20260301-007"
#endif /* AVUTIL_FFVERSION_H */
